language: node_js
branches:
  only:
  - master
notifications:
  email: true
cache:
  directories:
    - node_modules
node_js:
- '8'
script:
- npm run build
deploy:
  provider: firebase
  token:
    secure: "${FIREBASE_TOKEN}"
  message: "${TRAVIS_COMMIT}"

